// actionType.js

export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const UPDATE_STOCK = 'UPDATE_STOCK';

export const CREATE_INGREDIENT_REQUEST = 'CREATE_INGREDIENT_REQUEST';
export const CREATE_INGREDIENT_SUCCESS = 'CREATE_INGREDIENT_SUCCESS';
export const CREATE_INGREDIENT_FAILURE = 'CREATE_INGREDIENT_FAILURE';